### ISSUE TITLE
I can't execute .jar file

### ISSUE THREAD

**Issue by i7strelok** [sergiss/omron-fins#1]
Hello,

Thank you for contribuite with your solution.

I'm trying to execute your .jar file which is in https://github.com/sergiss/omron-fins/tree/master/build

Of course, I have java installed but it doesn't work well.

Could you help me?

**Comment by sergiss** [comment]
Hello,

[omron-fins.jar](https://github.com/sergiss/omron-fins/tree/master/build) is not an executable file, it is a library. To use the library you must look at: [Cp1lFinsExample.java](https://github.com/sergiss/omron-fins/blob/master/example/com/delmesoft/cp1l/fins/Cp1lFinsExample.java)

Best regards

**Comment by i7strelok** [comment]
Thanks for your answer. 

Do you know if it is possible to get information from PLC with zone + bit ? for instance: DM108
