### ISSUE TITLE
Read 16bit registry

### ISSUE THREAD

**Issue by matteosmcp** [sergiss/omron-fins#2]
Hi Sergio, many thanks for your nice libs. 
I need to implement a new method to get access to a full registry set, so I need to subscrice a full memory location in 16bit mode (reading int instead of boolean). Can you help me?

**Comment by sergiss** [comment]
Hello,

Thank you so much for your kind words and for using my libraries!

Regarding your request, I regret to inform you that I am not actively developing this project at the moment. Therefore, I won't be able to assist you in implementing the new feature you need.

Although I cannot offer direct help, I encourage you to look to the user community or forums related to the project. Often, other developers or users might have solutions or helpful advice for what you are trying to accomplish.

I appreciate your understanding and wish you the best with your project.

Best regards,
Sergio
